language: r
cache: packages
apt_packages:
  - libgdal-dev
  - libproj-dev
notifications:
  email:
    on_success: never
    on_failure: always

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
